// <auto-generated />
// Generated by EmoTracker.SourceGenerators.KVPropertyGenerator.
// Do not edit this file by hand.
#nullable disable
#pragma warning disable CS0108 // member hides inherited member; the partial-property half is intentional

using System;
using System.Collections.Generic;

namespace Demo
{
    partial class GoldenSmoke
    {

        public partial string Tag
            => this.ImmutableData.GetValue<string>("Tag", default(string));

        public partial int Count
        {
            get => this.MutableData.GetValue<int>("Count", default(int));
            set
            {
                var __current = this.MutableData.GetValue<int>("Count", default(int));
                if (!global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__current, value))
                {
                    this.NotifyPropertyChanging(nameof(Count));
                    this.MutableData.SetValue<int>("Count", value);
                    this.NotifyPropertyChanged(nameof(Count));
                }
            }
        }

        public partial string Note
        {
            get => this.MutableData.GetValue<string>("Note", default(string));
            set
            {
                var __current = this.MutableData.GetValue<string>("Note", default(string));
                if (!global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__current, value))
                {
                    this.NotifyPropertyChanging(nameof(Note));
                    this.MutableData.SetValue<string>("Note", value);
                    this.Bumped();
                    this.NotifyPropertyChanged(nameof(Note));
                }
            }
        }

        public partial bool Toggle
        {
            get => this.GetTransactableProperty<bool>(nameof(Toggle));
            set
            {
                this.SetTransactableProperty<bool>(value, null, nameof(Toggle));
            }
        }

        public partial string Selected
        {
            get => this.GetTransactableProperty<string>(nameof(Selected));
            set
            {
                this.SetTransactableProperty<string>(value, _ => this.SelectedNoticed(), nameof(Selected));
            }
        }

        public partial double Width
        {
            get
            {
                if (this.MutableData.ContainsKey("Width"))
                    return this.MutableData.GetValue<double>("Width", default(double));
                return this.ImmutableData.GetValue<double>("Width__def", default(double));
            }
            set
            {
                var __current = this.Width;
                if (!global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(__current, value))
                {
                    this.NotifyPropertyChanging(nameof(Width));
                    this.MutableData.SetValue<double>("Width", value);
                    this.NotifyPropertyChanged(nameof(Width));
                }
            }
        }

        public partial string Background
        {
            get
            {
                if (this.MutableData.ContainsKey("Background"))
                    return this.MutableData.GetValue<string>("Background", default(string));
                return this.ImmutableData.GetValue<string>("Background__def", default(string));
            }
            set
            {
                var __current = this.Background;
                if (!global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__current, value))
                {
                    this.NotifyPropertyChanging(nameof(Background));
                    this.MutableData.SetValue<string>("Background", value);
                    this.BackgroundChanged();
                    this.NotifyPropertyChanged(nameof(Background));
                }
            }
        }
    }
}
